# Generated by Django 4.1.7 on 2023-03-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='img',
            field=models.ImageField(default='ddhhhdd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
